# railway.toml
# Place this file in ROOT folder

[build]
builder = "NIXPACKS"
nixpacksConfigPath = "backend"

[deploy]
startCommand = "cd backend && chmod +x start.sh && ./start.sh"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.healthcheck]
path = "/health"
timeout = 100
interval = 60